monolith/views/home.py
from flask import Blueprint, render_template
from stravalib import Client

from monolith.database import db, Run, Plan
from monolith.auth import current_user


home = Blueprint('home', __name__)


def _strava_auth_url(config):
	client = Client()
	client_id = config['STRAVA_CLIENT_ID']
	redirect = 'http://127.0.0.1:5000/strava_auth'
	url = client.authorization_url(client_id=client_id, redirect_uri=redirect)
	return url

@home.route('/')
def index():
	if current_user is not None and hasattr(current_user, 'id'):
		runs = db.session.query(Run).filter(Run.runner_id == current_user.id)
		plans = db.session.query(Plan.start_date,Plan.end_date, Plan.distance).filter(Plan.runner_id == current_user.id)
		stat1 = compare()
		left = distance_left()
		plans = [plan+(left[i],) for i, plan in enumerate(plans)]
		avg = average_speed()
	else:
		runs = None
		plans = None
		avg = None
		stat1 = None
	strava_auth_url = _strava_auth_url(home.app.config)
	return render_template("index.html", runs=runs, plans=plans, stat1=stat1, avg=avg, strava_auth_url=strava_auth_url)

@home.route('/run/<id>', methods=['GET'])
def run(id):
	name    = None
	date    = None
	values  = None

	run = db.session.query(Run).filter(Run.runner_id == current_user.id).filter(Run.id == id).first()
	if run is not None:
		name    = run.name
		date    = run.start_date.strftime('%A %d/%m/%y at %H:%M')
		values  = [run.distance, run.average_speed, run.elapsed_time, run.total_elevation_gain]

	return render_template("run.html",name=name,date=date,values=values,id=run.id)
	# return render_template("index.html", runs=runs, strava_auth_url=strava_auth_url)

def compare():
	runs = db.session.query(Run).filter(Run.runner_id == current_user.id)
	best=0
	run_id=0
	if runs is None:
		print("do nothing")
	else:
		for run in runs:
			if run.distance > best:
				best=run.distance
				run_id=run.id

		bwrd=db.session.query(Run).filter(Run.id == run_id)

	return bwrd

def distance_left():
	runs = db.session.query(Run).filter(Run.runner_id == current_user.id)
	plans = db.session.query(Plan).filter(Plan.runner_id == current_user.id)
	distances_left = ()
	for plan in plans:
		yet_toRun = plan.distance
		for run in runs:
			if run.start_date.date() >= plan.start_date and run.start_date.date() <= plan.end_date:
				yet_toRun -= run.distance/1000
		if yet_toRun < 0:
			yet_toRun = 0
		distances_left+=(yet_toRun,)

	return distances_left

def average_speed():
	runs = db.session.query(Run).filter(Run.runner_id == current_user.id)
	avg = 0
	i = 0
	for run in runs:
		avg += run.average_speed*3.6
		i+=1

	if i == 0:
		return 0

	return avg/i

monolith/views/plan.py
from flask import Blueprint, redirect, render_template, request
from monolith.database import db, Plan
from monolith.forms import PlanForm
from monolith.auth import current_user

plan = Blueprint('plan', __name__)

@plan.route('/plan', methods=['GET', 'POST'])
def create_plan():
    form = PlanForm()
    if request.method == 'POST':

        if form.validate_on_submit():
            if current_user is not None and hasattr(current_user, 'id'):
                new_plan = Plan()
                new_plan.runner_id = current_user.id
                form.populate_obj(new_plan)
                db.session.add(new_plan)
                db.session.commit()
                return redirect('/')

    return render_template('plan.html', form=form)

monolith/views/report.py
from flask import Blueprint, redirect, render_template, request
from monolith.forms import ReportForm
from flask_login import current_user
from monolith.database import db

report = Blueprint('report', __name__)


@report.route('/report', methods=['GET', 'POST'])
def create_report():
    form = ReportForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            current_user.set_email_frequency(form.frequency.data)
            db.session.add(current_user)
            db.session.commit()
            return redirect('/')

    return render_template('report.html', form=form)

monolith/views/users.py
from flask import Blueprint, redirect, render_template, request
from monolith.database import db, User
from monolith.auth import admin_required
from monolith.forms import UserForm
from monolith.forms import LoginForm
from flask_login import current_user


users = Blueprint('users', __name__)


@users.route('/users')
def _users():
    users = db.session.query(User)
    return render_template("users.html", users=users)


@users.route('/create_user', methods=['GET', 'POST'])
def create_user():
    form = UserForm()
    if request.method == 'POST':

        if form.validate_on_submit():
            new_user = User()
            form.populate_obj(new_user)
            new_user.set_password(form.password.data) #pw should be hashed with some salt
            db.session.add(new_user)
            db.session.commit()
            return redirect('/users')

    return render_template('create_user.html', form=form)

# 1.5
@users.route('/delete_user', methods=['GET', 'POST'])
def delete_user():
    if current_user.is_authenticated:
        db.session.delete(current_user)
        db.session.commit()
    return redirect('/')

monolith/templates/create_user.html
<html>
 <body>
  <form action="" method="POST">
    {{ form.hidden_tag() }}
    <dl>
     {% for field in form.display %}
     <dt>{{ form[field].label }}</dt>
     <dd>{{ form[field]() }}</dd>
       {% if form[field].errors %}
          {% for e in form[field].errors %}
           <p class="help-block">{{ e }}</p>
          {% endfor %}
       {% endif %}
     {% endfor %}
    </dl>
    <p>
    <input type=submit value="Publish">
  </form>
 </body>
</html>

monolith/templates/index.html
<h1>BeepBeep</h1>

<style>
	table, th, td{
		border:1px solid black;
	}

</style>
{% if current_user.is_authenticated %}
	Hi {{ current_user.email }}! <a href="/report"> E-mail report</a> <a href="/delete_user"> Delete me!</a> <a href="/logout">Log out</a>

	{% if not current_user.strava_token %}
		<a href="{{strava_auth_url}}">Authorize Strava Access</a>
	{% else %}

		<h2>Your last 10 runs</h2>

		{% for run in runs%}
			<div>
			 <a href="{{url_for('home.run', id=run.id)}}">{{run.name}}</a>
			</div>
		{% endfor %}

		<h2>Training objectives</h2>
		<a href="{{url_for('plan.create_plan')}}">Create a plan</a>

		{% for plan in plans %}
			<div>
			 start: {{plan[0]}}, end: {{plan[1]}}, distance: {{plan[2]}} Km, remaining: {{plan[3]}} Km
			</div>
		{% endfor %}

		<h3 style="color:brown;">
			Running Statistics</h3>
		<table style="width:100%">
		<tr>
			<th>Run name</th>
			<th>Date</th>
			<th>Distance Covered</th>
			<th>Average Speed</th>
			<th>Elapsed Time</th>
		</tr>

		{% for run in runs%}
		<tr>
			<td>{{run.name}}</td>
			<td>{{run.start_date}}</td>
			<td>{{run.distance/1000}} Km </td>
			<td>{{run.average_speed*3.6}} Km/h </td>
			<td>{{run.elapsed_time/60}} Minutes</td>
		</tr>
		{% endfor %}
		</table>

		<h4 style="color:rgb(64,0,0);">
			you covered lot of distance. Best run so far you can do much better :)
		</h4>

		<table style="width:100%">
		<tr>
			<th>Run name</th>
			<th>Date</th>
			<th>Distance Covered</th>
			<th>Average Speed</th>
			<th>Elapsed Time</th>
		</tr>

		{% for run in stat1%}
			<tr>
				<td>{{run.name}}</td>
				<td>{{run.start_date}}</td>
				<td>{{run.distance/1000}} Km </td>
				<td>{{run.average_speed*3.6}} Km/h </td>
				<td>{{run.elapsed_time/60}} Minutes</td>
			</tr>
		{% endfor %}
		</table>
		<h4>Average speed of all runs: {{avg}} Km/h</h4>
	{% endif %}
{% else %}
	Hi Anonymous, <a href="/login">Log in</a>
{% endif %}

monolith/templates/login.html
<html>
 <body>
  <form action="" method="POST">
    {{ form.hidden_tag() }}
    <dl>
     {% for field in form.display %}
     <dt>{{ form[field].label }}</dt>
     <dd>{{ form[field]() }}</dd>
       {% if form[field].errors %}
          {% for e in form[field].errors %}
           <p class="help-block">{{ e }}</p>
          {% endfor %}
       {% endif %}
     {% endfor %}
    </dl>
    <p>
    <input type=submit value="Publish">
  </form>
 </body>
</html>

monolith/templates/plan.html
<html>
 <body>
  <form action="" method="POST">
    {{ form.hidden_tag() }}
    <dl>
     {% for field in form.display %}
     <dt>{{ form[field].label }}</dt>
     <dd>{{ form[field]() }}</dd>
       {% if form[field].errors %}
          {% for e in form[field].errors %}
           <p class="help-block">{{ e }}</p>
          {% endfor %}
       {% endif %}
     {% endfor %}
    </dl>
    <p>
    <input type=submit value="Publish">
  </form>
 </body>
</html>

monolith/templates/report.html
<html>
 <body>
  <form action="" method="POST">
    Hi {{ current_user.email }}! Configure how often you would like to receive your periodic report via e-mail!
    {{ form.hidden_tag() }}
    <dl>
     {% for field in form.display %}
     <dt>{{ form[field].label }}</dt>
     <dd>{{ form[field]() }}</dd>
       {% if form[field].errors %}
          {% for e in form[field].errors %}
           <p class="help-block">{{ e }}</p>
          {% endfor %}
       {% endif %}
     {% endfor %}
    </dl>
    <p>
    <input type=submit value="Set the frequency">
  </form>
 </body>
</html>

monolith/templates/run.html
<html>
  <head>
    <!--<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">-->
  </head>
  <h1>Last Previous Run</h1>
  <body>

   <div>

     Run :       &nbsp           {{ id }} <br />
     {% if not name %}
     <!--<h1>Resource requested is unavailable!</h1>-->
     {% else %}

     Name : {{ name }}  <br/>
     Date : {{ date }} <br/>
     Distance : {{ values[0]/1000}} Km <br/>
     Average_Speed : {{ values[1]*3.6 }} Km/h<br/>
     Elapsed_Time  : {{ values[2] }} minutes<br/>
     Total_Elevation_Gain : {{ values[3] }} meters<br/>
   </div>
    {% endif %}
  </body>
</html>

monolith/templates/users.html
<html>
  <body>
    <h1>User List</h1>
    <ul>
      {% for user in users: %}
      <li>
      {{user.firstname}} {{user.lastname}}
      </li>
      {% endfor %}
    </ul>
  </body>
</html>